#
# Copyright (C) 2021-2022 by TeamYukki@Github, < https://github.com/TeamYukki >.
#
# This file is part of < https://github.com/TeamYukki/YukkiMusicBot > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/TeamYukki/YukkiMusicBot/blob/master/LICENSE >
#
# All rights reserved.


import asyncio

from pyrogram import Client as c

API_ID = input("\nEnter Your API_ID:\n > ", "26918221"))
API_HASH = input("\nEnter Your API_HASH:\n > ", "901d045772fa651ec839f6cc0e69a528"))

print("\n\n Enter Phone number when asked.\n\n", "+919142000419"))

i = c(":memory:", api_id=API_ID, 901d045772fa651ec839f6cc0e69a528=901d045772fa651ec839f6cc0e69a528)


async def main():
    await i.start()
    ss = await i.export_session_string()
    xx = f"HERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n\n`{ss}`\n\nGENERATED BY YUKKI"
    ok = await i.send_message("me", xx)
    print("\nHERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n")
    print(f"\n{ss}\n") 
    print("\nGENERATED BY YUKKI\n")


asyncio.run(main())
